const MILLISECONDS_PER_SECOND = 1000;
const SECONDS_PER_MINUTE = 60;
const MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * SECONDS_PER_MINUTE;

export { MILLISECONDS_PER_MINUTE, MILLISECONDS_PER_SECOND, SECONDS_PER_MINUTE };
